parameters:
    pim_connector.reader.dummy_item.class:    Pim\Component\Connector\Reader\DummyItemReader
    pim_connector.reader.doctrine.base.class: Pim\Component\Connector\Reader\Doctrine\BaseReader

    pim_connector.reader.file.csv.class:         Pim\Component\Connector\Reader\File\CsvReader
    pim_connector.reader.file.csv_product.class: Pim\Component\Connector\Reader\File\CsvProductReader

    pim_connector.reader.file.xlsx.class:         Pim\Component\Connector\Reader\File\XlsxReader
    pim_connector.reader.file.xlsx_product.class: Pim\Component\Connector\Reader\File\XlsxProductReader

    pim_connector.reader.file.file_iterator.class: Pim\Component\Connector\Reader\File\FileIterator

services:
    pim_connector.reader.file.csv_iterator:
        class: %pim_connector.reader.file.file_iterator.class%
        arguments:
            - 'csv'

    pim_connector.reader.file.xlsx_iterator:
        class: %pim_connector.reader.file.file_iterator.class%
        arguments:
            - 'xlsx'

    # Dummy Reader
    pim_connector.reader.dummy_item:
        class: %pim_connector.reader.dummy_item.class%

    # CSV File Readers
    pim_connector.reader.file.csv:
        class: %pim_connector.reader.file.csv.class%
        arguments:
            - '@pim_connector.reader.file.csv_iterator'

    pim_connector.reader.file.csv_association_type:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_family:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_association:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_attribute:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_attribute_option:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_group:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_variant_group:
        alias: pim_connector.reader.file.csv_product

    pim_connector.reader.file.csv_category:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_channel:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_locale:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_attribute_group:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_group_type:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_currency:
        alias: pim_connector.reader.file.csv

    pim_connector.reader.file.csv_product:
        class: %pim_connector.reader.file.csv_product.class%
        arguments:
            - '@pim_connector.reader.file.csv_iterator'
            - '@pim_catalog.repository.attribute'
            - %pim_catalog.localization.decimal_separators%
            - %pim_catalog.localization.date_formats%

    # XLSX file Readers
    pim_connector.reader.file.xlsx:
        class: %pim_connector.reader.file.xlsx.class%
        arguments:
            - '@pim_connector.reader.file.xlsx_iterator'

    pim_connector.reader.file.xlsx_product:
       class: %pim_connector.reader.file.xlsx_product.class%
       arguments:
           - '@pim_connector.reader.file.xlsx_iterator'
           - '@pim_catalog.repository.attribute'
           - %pim_localization.decimal_separators%
           - %pim_localization.date_formats%

    pim_connector.reader.file.xlsx_association:
        alias: pim_connector.reader.file.xlsx
